# Generated by Django 4.2.2 on 2023-10-01 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0002_book_barcode"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reviews",
            name="book",
        ),
        migrations.RemoveField(
            model_name="reviews",
            name="student",
        ),
        migrations.RemoveField(
            model_name="book",
            name="author",
        ),
        migrations.RemoveField(
            model_name="book",
            name="genre",
        ),
        migrations.RemoveField(
            model_name="book",
            name="language",
        ),
        migrations.RemoveField(
            model_name="book",
            name="pic",
        ),
        migrations.RemoveField(
            model_name="book",
            name="summary",
        ),
        migrations.RemoveField(
            model_name="book",
            name="total_copies",
        ),
        migrations.DeleteModel(
            name="Borrower",
        ),
        migrations.DeleteModel(
            name="Genre",
        ),
        migrations.DeleteModel(
            name="Language",
        ),
        migrations.DeleteModel(
            name="Reviews",
        ),
        migrations.DeleteModel(
            name="Student",
        ),
    ]
